### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Suleman-Elahi** [obra/Youtube2Webpage#17]
`Can't open '<undef>' for reading: 'No such file or directory' at ./yt-to-webpage.pl line 21`

![image](https://github.com/obra/Youtube2Webpage/assets/24384996/b1c36392-180f-4630-a20c-f863c398f7b0)

**Comment by obra** [comment]
As of now, the tool has really only been tested in unixlike enviornments.  If you'd like to run it on windows, WSL is probably your best bet.

(I'd be happy to take a pull request to port to windows)
