### ISSUE TITLE
Can someone please help me understand this repository?

### ISSUE THREAD

**Issue by ItsPiyusha** [obra/Youtube2Webpage#2]

**Comment by halas** [comment]
As in what it does or how it does it? 
As far as I understand this is a Perl script that given the url to youtube video chops this video into frames taken every second acompanied by captions and outputs a web page (html, images, css) showing it. 
So for example when you have a video tutorial but (like me) don't like geting your information from video tutorials and prefer easily scrollable articles on web pages - this kinda converts video tutorial to an article.

**Comment by le-jun** [comment]
The readme has been expanded https://github.com/obra/Youtube2Webpage/pull/8, I think this issue can be closed.

**Comment by obra** [comment]
@Suleman-Elahi  - The tool is a single script that's designed to run in place. It does not need to be installed. (But also, please open new issues for new issues.)
