### ISSUE TITLE
Feature requested - Download subtitles only

### ISSUE THREAD

**Issue by OrionRandD** [obra/Youtube2Webpage#26]
Could you provide a feature to download only the subtitles and no images at all?
Especially to people who runs the script in low-end computers with not much space on their SSDs, like me.
A video like this one that is not that long, is impossible to grab in here... because there are too many screenshots to be downloaded 
https://www.youtube.com/watch?v=1mXmVJkk4Dc&t=1222
Thx...

**Comment by obra** [comment]
if all you want is to download the transcript, you can use something like youtube-dlp. On May 12, 2024, at 7:49 AM, OrionRandD ***@***.***> wrote:﻿
Could you provide a feature to download only the subtitles and no images at all?
Especially to people who runs the script in low-end computers with not much space on their SSDs, like me.
Thx...

**Comment by OrionRandD** [comment]
> if all you want is to download the transcript, you can use something like youtube-dlp. On May 12, 2024, at 7:49 AM, OrionRandD ***@***.***> wrote:﻿ Could you provide a feature to download only the subtitles and no images at all? Especially to people who runs the script in low-end computers with not much space on their SSDs, like me. Thx... —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thx, 
I forgot that...
