### ISSUE TITLE
Support for non-Youtube services

### ISSUE THREAD

**Issue by le-jun** [obra/Youtube2Webpage#6]
Is there any plan to support non-Youtube services? Or even Youtube-frontends such as Invidious?

**Comment by obra** [comment]
I’ll happily take patches for any service that can serve us subtitles and a downloadable video. On Aug 3, 2023, at 1:04 AM, LeJun ***@***.***> wrote:﻿
Is there any plan to support non-Youtube services? Or even Youtube-frontends such as Invidious?

**Comment by le-jun** [comment]
My bad, didn't see how the script relied upon closed captions. Thought it was some kind of speech-to-text.
